# Generated by Django 4.2.11 on 2024-03-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sentence', models.CharField(max_length=2500)),
                ('document', models.CharField(max_length=250)),
                ('constraint', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
