# Generated by Django 4.2.11 on 2024-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='job_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
